services:

  nginx:
    build:
      context: .
    container_name: nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # For Let's Encrypt SSL certs
      - ./certbot/www:/var/www/certbot    # For Certbot validation
    ports:
      - "80:80"
  
  certbot-init:
    image: certbot/certbot
    container_name: certbot-init
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'certbot certonly --webroot -w /var/www/certbot -d subdomain.example.com --agree-tos -m email@example.com --no-eff-email'"
    depends_on:
      - nginx

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h; done"
